function [x_vals] = military_budget(x0, num_steps, params)

% extract all values from the "struct" and assign them to regular variables
a = params.a; b = params.b; K = params.K;
L = params.L; g = params.g; h = params.h;

% Inputs:
% > x0 is a 2x1 column vector containing the initial military budgets of
%   both countries.
% > num_steps is the number of times the iterated map is applied
% > params is a "struct" containing parameter values (a, b, K, L, g, h)
% initial values
x_vals = zeros(2, num_steps + 1);
x_vals(:, 1) = x0;

% Outputs:
% > p_vals is a 2 x (num_steps + 1) array, i.e. 2 rows and num_steps+1
%   columns. The first column of x_vals is the initial condition, 
%   and the values of x^(k) generated by the iterated map in eq. (13) are
%   the other columns (in chronological order)
for k = 1:num_steps
    x1_k1 = ((1-a) * x_vals(1, k)) + (K*x_vals(2, k) + g);
    x2_k1 = (L*x_vals(1,k)) + ((1 - b) * x_vals(2, k) + h);
    x_vals(:, k + 1) = [x1_k1; x2_k1];
end

end